using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player : MonoBehaviour
{
    public static Player Instance { get; private set; }

    PlayerMovement playerMovement;

    Animator animator;

    void Awake() {
        if (Instance != null && Instance != this) { 
            Destroy(this);
        } else { 
            Instance = this;
        }
    }

    
    void Start() {
        playerMovement = GetComponent<PlayerMovement>();
        animator = GameObject.Find("EngineEffect").GetComponent<Animator>();
        //animator = GetComponentInChildren<Animator>();
    }
    
    void FixedUpdate() {
        playerMovement.Move();
    }

    void LateUpdate() {
        playerMovement.MoveBound();
        animator.SetBool("IsMoving", playerMovement.IsMoving());
    }
}
